"""tbl_master_ReportDesign-> valueT column added

Revision ID: 56cf6110bc85
Revises: 02d91aad7280
Create Date: 2024-10-17 11:35:42.465464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cf6110bc85'
down_revision = '02d91aad7280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_master_EmployeeAddress',
    sa.Column('SNO', sa.Integer(), nullable=False),
    sa.Column('EmployeeCode', sa.String(length=20), nullable=True),
    sa.Column('AddressType', sa.String(length=20), nullable=True),
    sa.Column('Mobile', sa.String(length=20), nullable=True),
    sa.Column('Email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('SNO'),
    schema='VisitorTrack'
    )
    op.create_table('tbl_master_EmployeeMain',
    sa.Column('SNO', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EmployeeCode', sa.String(length=50), nullable=True),
    sa.Column('AlternateCode', sa.String(length=50), nullable=True),
    sa.Column('ShortName', sa.String(length=50), nullable=True),
    sa.Column('FirstName', sa.String(length=30), nullable=True),
    sa.Column('MiddleName', sa.String(length=30), nullable=True),
    sa.Column('LastName', sa.String(length=50), nullable=True),
    sa.Column('DateofBirth', sa.DateTime(), nullable=True),
    sa.Column('DateofJoining', sa.DateTime(), nullable=True),
    sa.Column('Company', sa.String(length=50), nullable=True),
    sa.Column('Department', sa.String(length=50), nullable=True),
    sa.Column('Designation', sa.String(length=50), nullable=True),
    sa.Column('Category', sa.String(length=50), nullable=True),
    sa.Column('EmailID', sa.String(length=50), nullable=True),
    sa.Column('ContactNo', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('SNO'),
    schema='VisitorTrack'
    )
    op.create_table('tbl_master_ReportDesign',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Menu', sa.String(length=100), nullable=True),
    sa.Column('Description', sa.String(length=100), nullable=True),
    sa.Column('UserId', sa.String(length=50), nullable=True),
    sa.Column('Config', sa.Text(), nullable=True),
    sa.Column('Value', sa.Text(), nullable=True),
    sa.Column('ValueTwo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='VisitorTrack'
    )
    op.create_table('tbl_master_Settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Menu', sa.String(length=100), nullable=True),
    sa.Column('Description', sa.String(length=100), nullable=True),
    sa.Column('UserId', sa.String(length=50), nullable=True),
    sa.Column('Orientation', sa.String(length=50), nullable=True),
    sa.Column('PageSize', sa.String(length=50), nullable=True),
    sa.Column('Config', sa.Text(), nullable=True),
    sa.Column('Value', sa.Text(), nullable=True),
    sa.Column('ValueTwo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='VisitorTrack'
    )
    op.create_table('tbl_master_Userperms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=50), nullable=True),
    sa.Column('UPassword', sa.String(length=10), nullable=True),
    sa.Column('EmployeeCode', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='VisitorTrack'
    )
    op.create_table('vis_tbl_master_Company',
    sa.Column('SNO', sa.Integer(), nullable=False),
    sa.Column('Company', sa.String(length=100), nullable=True),
    sa.Column('AddressLine1', sa.String(length=100), nullable=True),
    sa.Column('AddressLine2', sa.String(length=100), nullable=True),
    sa.Column('Area', sa.String(length=50), nullable=True),
    sa.Column('City', sa.String(length=50), nullable=True),
    sa.Column('State', sa.String(length=50), nullable=True),
    sa.Column('Country', sa.String(length=50), nullable=True),
    sa.Column('PinCode', sa.String(length=50), nullable=True),
    sa.Column('Contact1', sa.String(length=50), nullable=True),
    sa.Column('Contact2', sa.String(length=50), nullable=True),
    sa.Column('Phone', sa.String(length=50), nullable=True),
    sa.Column('Fax', sa.String(length=50), nullable=True),
    sa.Column('Mobile', sa.String(length=50), nullable=True),
    sa.Column('Email', sa.String(length=50), nullable=True),
    sa.Column('WebSite', sa.String(length=250), nullable=True),
    sa.Column('TypeOfService', sa.String(length=50), nullable=True),
    sa.Column('TypeOfIndustry', sa.String(length=50), nullable=True),
    sa.Column('Active', sa.String(length=50), nullable=True),
    sa.Column('InActiveDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('VisitorType', sa.String(length=50), nullable=True),
    sa.Column('ContractEndDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('SNO'),
    schema='VisitorTrack'
    )
    op.create_table('vis_tbl_master_Visitors',
    sa.Column('SNO', sa.Integer(), nullable=False),
    sa.Column('VisitorName', sa.String(length=100), nullable=True),
    sa.Column('Company', sa.String(length=100), nullable=True),
    sa.Column('VisitorCategory', sa.String(length=100), nullable=True),
    sa.Column('MobileNumber', sa.String(length=100), nullable=True),
    sa.Column('EmailID', sa.String(length=100), nullable=True),
    sa.Column('FirstVisitDate', sa.String(length=100), nullable=True),
    sa.Column('LastVisitDate', sa.String(length=100), nullable=True),
    sa.Column('IDCardType', sa.String(length=100), nullable=True),
    sa.Column('IDCardNumber', sa.String(length=100), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('SNO'),
    schema='VisitorTrack'
    )
    op.create_table('vis_tbl_trans_VistorLog24',
    sa.Column('SNO', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('IDCardImageName', sa.String(length=100), nullable=True),
    sa.Column('VisitorID', sa.String(length=50), nullable=True),
    sa.Column('CompanyID', sa.String(length=50), nullable=True),
    sa.Column('PassNumber', sa.String(length=50), nullable=True),
    sa.Column('PassDate', sa.DateTime(), nullable=True),
    sa.Column('BadgeNumber', sa.String(length=50), nullable=True),
    sa.Column('Company', sa.String(length=100), nullable=True),
    sa.Column('VisitorName', sa.String(length=100), nullable=True),
    sa.Column('VisCategory', sa.String(length=100), nullable=True),
    sa.Column('MobileNumber', sa.String(length=100), nullable=True),
    sa.Column('VisTotal', sa.String(length=100), nullable=True),
    sa.Column('VisPurpose', sa.String(length=100), nullable=True),
    sa.Column('VehicleNumber', sa.String(length=100), nullable=True),
    sa.Column('VisAdditional', sa.String(length=100), nullable=True),
    sa.Column('ReturnableItems', sa.Text(), nullable=True),
    sa.Column('VehicleNo', sa.String(length=100), nullable=True),
    sa.Column('EmployeeCode', sa.String(length=100), nullable=True),
    sa.Column('Department', sa.String(length=100), nullable=True),
    sa.Column('InTime', sa.DateTime(), nullable=True),
    sa.Column('OutTime', sa.DateTime(), nullable=True),
    sa.Column('ImageName', sa.String(length=100), nullable=True),
    sa.Column('AppointmentNumber', sa.String(length=100), nullable=True),
    sa.Column('VehcileType', sa.String(length=50), nullable=True),
    sa.Column('VehicleCompany', sa.String(length=50), nullable=True),
    sa.Column('DriverName', sa.String(length=50), nullable=True),
    sa.Column('CabInTime', sa.String(length=50), nullable=True),
    sa.Column('CabOutTime', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('SNO'),
    schema='VisitorTrack'
    )
    op.drop_table('tbl_master_report_design')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_master_report_design',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('menu', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('userid', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('config', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('valuetwo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tbl_master_report_design_pkey')
    )
    op.drop_table('vis_tbl_trans_VistorLog24', schema='VisitorTrack')
    op.drop_table('vis_tbl_master_Visitors', schema='VisitorTrack')
    op.drop_table('vis_tbl_master_Company', schema='VisitorTrack')
    op.drop_table('tbl_master_Userperms', schema='VisitorTrack')
    op.drop_table('tbl_master_Settings', schema='VisitorTrack')
    op.drop_table('tbl_master_ReportDesign', schema='VisitorTrack')
    op.drop_table('tbl_master_EmployeeMain', schema='VisitorTrack')
    op.drop_table('tbl_master_EmployeeAddress', schema='VisitorTrack')
    # ### end Alembic commands ###
